### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Wunderharke** [NichtPonczek/AutoSpeak-a-Ts3-bot#1]
Hi @NichtPonczek 

first of all: this is an awesome project! there are so many functions.
I've took a look in there, but is overwhelming.

Are you panning to have something like a documentation for this project?

The config file is some kind of standpoint but a structured installation & setup documentation would be very helpful.

**Comment by NichtPonczek** [comment]
@Wunderharke ./start.sh install is the fastest way to install everything in one shot i'll also typed some basic stuff at `https://github.com/NichtPonczek/AutoSpeak-a-Ts3-bot/wiki` if there's not enough info just contact me & i'll try my best to create a bit more of the documentation

**Comment by Wunderharke** [comment]
Hey okay SQL is working and scripts are starting up.
Rest of configuration is done in config.php?

Is there a way to integrate with identity management like ldap?

**Comment by NichtPonczek** [comment]
yeah all of the configuration is done through config.php
i'll don't know if the bot would work with an identity management configuration it is's possible the bot would run fine but on the other hand the bot might break and simply don't work

**Comment by rafalohaki** [comment]
+1
