### ISSUE TITLE
Instance base channels

### ISSUE THREAD

**Issue by rafalohaki** [NichtPonczek/AutoSpeak-a-Ts3-bot#2]
Updater: [ERROR #Ch1:941] - support_channels() 
Channels: [SYSTEM] Admin query błąd
Base: [SYSTEM] Admin query błąd
Proszę o pomoc.

**Comment by NichtPonczek** [comment]
Updater: [ERROR #Ch1:941] - support_channels() to wskazuje na brak kanału  1 oraz grupy 941 ale możesz to zignorować winna temu jest któraś z zintegrowanych w bota bibliotek  
Channels: [SYSTEM] Admin query błąd
Base: [SYSTEM] Admin query błąd
Wskazuje na błąd połączenia z ts3 sprawdź co pokaże php core.php -i 3 oraz php core.php -i 4

**Comment by rafalohaki** [comment]
![image](https://user-images.githubusercontent.com/20607107/78457384-080fea00-76aa-11ea-8170-1d85e2f575a4.png)
admin i updater niby działają i widać na serwerze

**Comment by NichtPonczek** [comment]
niestety nie udało mi się odtworzyć problemu sprawdź czy teamspeak nie blokuje połączenia bota za flood tak powinno wszystko przy poprawnym połączeniu wyglądać 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/55951669/78470899-98dfd780-7735-11ea-8d61-06fbca72d521.gif)
